### ISSUE TITLE
Responsibilities as Accountant

### ISSUE THREAD

**Issue by bacharakis** [lambdaspace/lambdaspace-taskmanager#14]
### Description (what is the goal of this issue) 
What do I have to do for the next week
### Action items 
- [x] Build a financial report for 2017 and send it to members for review
- [x] Gather review and update it accordingly 
- [x] Send a reminder for subscriptions for this month (@panagiks )

### Links/resources 
any relevant links/resources

**Comment by AEtherC0r3** [comment]
@panagiks ping

**Comment by panagiks** [comment]
No changes requested on the provided report, closing it as done.
