### ISSUE TITLE
Members on boarding

### ISSUE THREAD

**Issue by bacharakis** [lambdaspace/lambdaspace-taskmanager#2]
### Description (what is the goal of this issue) 
Draft a guide/steps and reach out to members applied

### Action items 
- [x] Reach out to members applied
- [x] Create a message template for new members applied
- [x] Find out mentors to connect
- [x] Find a time for new members to meet

### Links/resources 
any relevant links/resources

**Comment by bacharakis** [comment]
I followed up again with all the members applied. 1 came to the space last week, the other 2 haven't replied yet or didn't show up in the online chat.

**Comment by bacharakis** [comment]
New members template: Feel free to edit, change, update: https://github.com/lambdaspace/lambdaspace-taskmanager/blob/master/new_member.email

**Comment by bacharakis** [comment]
@alexdor @AEtherC0r3  Are you interested becoming a mentor of the new member who you met last week?

**Comment by alexdor** [comment]
Yep

**Comment by AEtherC0r3** [comment]
Yes
